# Generated by Django 4.1.1 on 2022-09-20 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='images/')),
                ('text', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('groups', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Moliya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('tuliv', models.SmallIntegerField(choices=[(1, 'Qariz'), (2, 'Tuliq')])),
                ('students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.students')),
                ('yaer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.year')),
            ],
        ),
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kun', models.CharField(max_length=250)),
                ('students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.students')),
                ('yaer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.year')),
            ],
        ),
    ]
