# Generated by Django 4.1.1 on 2022-09-22 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=250)),
                ('tuliv', models.SmallIntegerField(choices=[(1, 'Qariz'), (2, 'Tuliq')])),
                ('groups', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.groups')),
                ('students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.students')),
                ('yaer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.year')),
            ],
        ),
    ]
